# =========================
# Basic Site Settings
# =========================
locale        : "en-US"
site_theme    : "air"                         # Minimal, spacious look
title         : "Lei Cheng"
title_separator: "–"
name          : &name "Lei Cheng"
description   : &description "Sensor Fusion • Calibration • Radar/LiDAR/Camera • Intelligent Transportation"
url           : "https://leicheng5.github.io" # Your site base URL
baseurl       : ""                            # Keep empty for user sites
repository    : "leicheng5/leicheng5.github.io"

# =========================
# Author (sidebar profile)
# =========================
author:
  avatar       : "profile.png"                # Put this image in /images or /assets/images
  name         : "Lei Cheng"
  pronouns     :
  bio          : "Research Faculty @ UMD (MTI). Deep-learning–based heterogeneous sensor fusion for autonomous systems."
  location     : "College Park, MD, USA"
  employer     : "University of Maryland, MTI"
  uri          :
  email        : "you@example.com"            # TODO: replace with your email

  # Academic profiles (leave blank to hide)
  googlescholar: "https://scholar.google.com/citations?user=XXXXXXX"  # TODO
  orcid        : "https://orcid.org/0000-0000-0000-0000"              # TODO
  researchgate :
  scopus       :
  pubmed       :
  arxiv        :

  # Developer profiles
  github       : "leicheng5"
  kaggle       :
  stackoverflow:

  # Social (fill username only, or leave blank)
  linkedin     : "your-linkedin-username"     # TODO
  bluesky      :
  twitter      :
  youtube      :
  zhihu        :

# =========================
# Publication Categories
# =========================
publication_category:
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"
  books:
    title: "Books"

# =========================
# Site Settings
# =========================
teaser            :
breadcrumbs       : true                       # Helpful hierarchical navigation
words_per_minute  : 180
future            : true
read_more         : "disabled"
talkmap_link      : false

comments:
  provider        :                            # Disable comments for a cleaner look
  disqus:
    shortname     :
  discourse:
    server        :
  facebook:
    appid         :
    num_posts     :
    colorscheme   :

staticman:
  allowedFields   : ['name', 'email', 'url', 'message']
  branch          : "gh-pages"
  commitMessage   : "New comment."
  filename        : comment-{@timestamp}
  format          : "yml"
  moderation      : true
  path            : "_data/comments/{options.slug}"
  requiredFields  : ['name', 'email', 'message']
  transforms:
    email         : "md5"
  generatedFields:
    date:
      type        : "date"
      options:
        format    : "iso8601"

atom_feed:
  hide            : false
  path            :

# =========================
# SEO & Social
# =========================
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

twitter:
  username       :
facebook:
  username       :
  app_id         :
  publisher      :

og_image         :            # Optional: social share image (1200x630 recommended)
og_description   :            # Optional: fallback to site description if blank

social:
  type           : Person
  name           : "Lei Cheng"
  links:                         # Optional: full URLs listed below
    # - https://scholar.google.com/citations?user=XXXXXXX
    # - https://github.com/leicheng5
    # - https://www.linkedin.com/in/your-linkedin-username

# =========================
# Analytics
# =========================
analytics:
  provider       : "false"     # Set to "google-analytics-4" when ready
  google:
    tracking_id  :            # Example: G-XXXXXXXXXX

# =========================
# Reading / Build
# =========================
include:
  - .htaccess
  - _pages
  - files

exclude:
  - .github
  - node_modules
  - vendor
  - tmp
  - local
  - README
  - CHANGELOG
  - LICENSE
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - package.json*
  - Rakefile

keep_files:
  - .git
  - .svn

encoding        : "utf-8"
markdown_ext    : "markdown,mkdown,mkdn,mkd,md"

# =========================
# Markdown / Rendering
# =========================
markdown        : kramdown
highlighter     : rouge
lsi             : false
excerpt_separator: "\n\n"
incremental     : false

kramdown:
  input         : GFM
  hard_wrap     : false
  auto_ids      : true
  footnote_nr   : 1
  entity_output : as_char
  toc_levels    : 1..6
  smart_quotes  : lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# =========================
# Collections
# =========================
collections:
  teaching:
    output      : true
    permalink   : /:collection/:path/
  publications:
    output      : true
    permalink   : /:collection/:path/
  portfolio:
    output      : true
    permalink   : /:collection/:path/
  talks:
    output      : true
    permalink   : /:collection/:path/

# =========================
# Defaults (ensures sidebar on key pages)
# =========================
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout        : single
      author_profile: true
      read_time     : true
      comments      : false
      share         : true
      related       : true
  - scope:
      path: ""
      type: pages
    values:
      layout        : single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : false
  - scope:
      path: ""
      type: publications
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : false
  - scope:
      path: ""
      type: portfolio
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : false
  - scope:
    # talks use a custom layout shipped with academicpages
      path: ""
      type: talks
    values:
      layout        : talk
      author_profile: true
      share         : true
      comments      : false

# =========================
# Sass / Output
# =========================
sass:
  sass_dir : _sass
  style    : compressed

permalink : /:categories/:title/
timezone  : America/New_York   # Set your preferred timezone

# =========================
# Plugins
# =========================
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Needed when GitHub Pages runs in safe mode
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# =========================
# Archives
# =========================
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# =========================
# HTML Compression
# =========================
compress_html:
  clippings: all
  ignore:
    envs: development
